---
# tasks file for docker / centos

- name: Configure Docker repository
  yum_repository:
    name: Docker-CE-Stable
    baseurl: "{{ docker_repo_url }}"
    description: Docker CE Stable - $basearch
    gpgcheck: true
  register: status_docker_repo
  when: docker_repo

- name: Add Docker repository key
  rpm_key:
    key: "{{ docker_repo_key }}"
    state: present
  register: status_docker_repo
  when: docker_repo

- name: Install Docker CE
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
    update_cache: "{{ status_docker_repo.changed }}"

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker SDK
  pip:
    name: docker
    state: present
