---
# tasks file for docker / ubuntu

- name: Configure Docker APT repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    state: present
    update_cache: false
  register: status_docker_apt

- name: Add Docker APT repository key
  apt_key:
    url: "{{ docker_apt_repo_key }}"
    state: present
  register: status_docker_apt

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: "{{ status_docker_apt.changed }}"

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Make sure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install Docker SDK
  pip:
    name: docker
    state: present
